project = "bestbuy-product-catalog"
aws_region = "eu-central-1"
s3_bucket_name = "s3-bucket-6543"
data_engineer_iam_user = "data-engineer"
data_loader_iam_role = "data-loader"
data_loader_iam_policy = "data-loader-access-policy"